In [ ]:
################################################ Natural Language Processing ##################################################

In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [80]:
dataset = pd.read_csv('yelp.csv')

In [81]:
dataset

business_id        date               review_id  stars  \
0     9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1     ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
2     6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  IESLBzqUCLdSzSqm0eCSxQ      4   
3     _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4     6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   
...                      ...         ...                     ...    ...   
9995  VY_tvNUCCXGXQeSvJl757Q  2012-07-28  Ubyfp2RSDYW0g7Mbr8N3iA      3   
9996  EKzMHI1tip8rC1-ZAy64yg  2012-01-18  2XyIOQKbVFb6uXQdJ0RzlQ      4   
9997  53YGfwmbW73JhFiemNeyzQ  2010-11-16  jyznYkIbpqVmlsZxSDSypA      4   
9998  9SKdOoDHcFoxK5ZtsgHJoA  2012-12-02  5UKq9WQE1qQbJ0DJbc-B6Q      2   
9999  pF7uRzygyZsltbmVpjIyvw  2010-10-16  vWSmOhg2ID1MNZHaWapGbA      5   

                                                   text    type  \
0     My wife took me here on my birthday for breakf...  review   
1     I have no idea why some people give bad review...  review   
2     love the gyro plate. Rice is so good and I als...  review   
3     Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4     General Manager Scott Petello is a good egg!!!...  review   
...                                                 ...     ...   
9995  First visit...Had lunch here today - used my G...  review   
9996  Should be called house of deliciousness!\n\nI ...  review   
9997  I recently visited Olive and Ivy for business ...  review   
9998  My nephew just moved to Scottsdale recently so...  review   
9999  4-5 locations.. all 4.5 star average.. I think...  review   

                     user_id  cool  useful  funny  
0     rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1     0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
2     0hT2KtfLiobPvh6cDC8JQg     0       1      0  
3     uZetl9T0NcROGOyFfughhg     1       2      0  
4     vYmM4KTsC8ZfQBg-j5MWkw     0       0      0  
...                      ...   ...     ...    ...  
9995  _eqQoPtQ3e3UxLE4faT6ow     1       2      0  
9996  ROru4uk5SaYc3rg8IU7SQw     0       0      0  
9997  gGbN1aKQHMgfQZkqlsuwzg     0       0      0  
9998  0lyVoNazXa20WzUyZPLaQQ     0       0      0  
9999  KSBFytcdjPKZgXKQnYQdkA     0       0      0  

[10000 rows x 10 columns]

In [82]:
dataset_rating_1= dataset[dataset.stars ==1]

In [83]:
dataset_rating_1

business_id        date               review_id  stars  \
23    IJ0o6b8bJFAbG6MjGfBebQ  2010-09-05  Dx9sfFU6Zn0GYOckijom-g      1   
31    vvA3fbps4F9nGlAEYKk_sA  2012-05-04  S9OVpXat8k5YwWCn6FAgXg      1   
35    o1GIYYZJjM6nM03fQs_uEQ  2011-11-30  ApKbwpYJdnhhgP4NbjQw2Q      1   
61    l4vBbCL9QbGiwLuLKwD_bA  2011-11-22  DJVxOfj2Rw9zklC9tU3i1w      1   
64    CEswyP-9SsXRNLR9fFGKKw  2012-05-19  GXj4PNAi095-q9ynPYH3kg      1   
...                      ...         ...                     ...    ...   
9924  mhQCxOiqp03qnhGRTtPduw  2012-07-07  PCjnn__E8AzNa2kXFXxTHQ      1   
9931  C_eWAEOvkHZ_IZYGwjtpmg  2011-04-25  QfdoE-XqEeCsttJH8g0ugQ      1   
9953  QCxXYA13PtkD3wec47_r8Q  2012-03-14  V2N2TCqnaqMYfg7zXGG-Rg      1   
9984  wepFVY82q_tuDzG6lQjHWw  2012-02-12  spusZYROtBKw_5tv3gYm4Q      1   
9987  r-a-Cn9hxdEnYTtVTB5bMQ  2012-04-07  j9HwZZoBBmJgOlqDSuJcxg      1   

                                                   text    type  \
23    U can go there n check the car out. If u wanna...  review   
31    Disgusting!  Had a Groupon so my daughter and ...  review   
35    I've eaten here many times, but none as bad as...  review   
61    I have always been a fan of Burlington's deals...  review   
64    Another night meeting friends here.  I have to...  review   
...                                                 ...     ...   
9924                                  Horrible service.  review   
9931  I love Saddle Ranch for its casual night time ...  review   
9953  "Hipster,Trendy" ????-I think NOT !!!! Very di...  review   
9984  Went last night to Whore Foods to get basics t...  review   
9987  The food is delicious.  The service:  discrimi...  review   

                     user_id  cool  useful  funny  
23    zRlQEDYd_HKp0VS3hnAffA     0       1      1  
31    8AMn6644NmBf96xGO3w6OA     0       1      0  
35    iwUN95LIaEr75TZE_JC6bg     0       4      3  
61    EPROVap0M19Y6_4uf3eCmQ     0       0      0  
64    MjLAe48XNfYlTeFYca5gMw     0       1      2  
...                      ...   ...     ...    ...  
9924  rvaJcf5OIY2So_pkoqDHLQ     0       1      0  
9931  yhGfcKunPjcy-v-1ppr6oQ     0       2      0  
9953  JEQ6el2-tLtKJU6k_SpE-w     0       2      0  
9984  W7zmm1uzlyUkEqpSG7PlBw     0       1      2  
9987  toPtsUtYoRB-5-ThrOy2Fg     0       0      0  

[749 rows x 10 columns]

In [84]:
dataset_rating_5= dataset[dataset.stars ==5]

In [85]:
dataset_rating_5

business_id        date               review_id  stars  \
0     9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1     ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
3     _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4     6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   
6     zp713qNhx8d9KCJJnrw1xA  2010-02-12  riFQ3vxNpP4rWLk_CSri2A      5   
...                      ...         ...                     ...    ...   
9990  R8VwdLyvsp9iybNqRvm94g  2011-10-03  pcEeHdAJPoFNF23es0kKWg      5   
9991  WJ5mq4EiWYAA4Vif0xDfdg  2011-12-05  EuHX-39FR7tyyG1ElvN1Jw      5   
9992  f96lWMIAUhYIYy9gOktivQ  2009-03-10  YF17z7HWlMj6aezZc-pVEw      5   
9994  L3BSpFvxcNf3T_teitgt6A  2012-03-19  0nxb1gIGFgk3WbC5zwhKZg      5   
9999  pF7uRzygyZsltbmVpjIyvw  2010-10-16  vWSmOhg2ID1MNZHaWapGbA      5   

                                                   text    type  \
0     My wife took me here on my birthday for breakf...  review   
1     I have no idea why some people give bad review...  review   
3     Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4     General Manager Scott Petello is a good egg!!!...  review   
6     Drop what you're doing and drive here. After I...  review   
...                                                 ...     ...   
9990  Yes I do rock the hipster joints.  I dig this ...  review   
9991  Only 4 stars? \n\n(A few notes: The folks that...  review   
9992  I'm not normally one to jump at reviewing a ch...  review   
9994  Let's see...what is there NOT to like about Su...  review   
9999  4-5 locations.. all 4.5 star average.. I think...  review   

                     user_id  cool  useful  funny  
0     rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1     0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
3     uZetl9T0NcROGOyFfughhg     1       2      0  
4     vYmM4KTsC8ZfQBg-j5MWkw     0       0      0  
6     wFweIWhv2fREZV_dYkz_1g     7       7      4  
...                      ...   ...     ...    ...  
9990  b92Y3tyWTQQZ5FLifex62Q     1       1      1  
9991  hTau-iNZFwoNsPCaiIUTEA     1       1      0  
9992  W_QXYA7A0IhMrvbckz7eVg     2       3      2  
9994  OzOZv-Knlw3oz9K5Kh5S6A     1       2      1  
9999  KSBFytcdjPKZgXKQnYQdkA     0       0      0  

[3337 rows x 10 columns]

In [86]:
dataset_1_and_5 = pd.concat([dataset_rating_1,dataset_rating_5])

In [87]:
dataset_1_and_5

business_id        date               review_id  stars  \
23    IJ0o6b8bJFAbG6MjGfBebQ  2010-09-05  Dx9sfFU6Zn0GYOckijom-g      1   
31    vvA3fbps4F9nGlAEYKk_sA  2012-05-04  S9OVpXat8k5YwWCn6FAgXg      1   
35    o1GIYYZJjM6nM03fQs_uEQ  2011-11-30  ApKbwpYJdnhhgP4NbjQw2Q      1   
61    l4vBbCL9QbGiwLuLKwD_bA  2011-11-22  DJVxOfj2Rw9zklC9tU3i1w      1   
64    CEswyP-9SsXRNLR9fFGKKw  2012-05-19  GXj4PNAi095-q9ynPYH3kg      1   
...                      ...         ...                     ...    ...   
9990  R8VwdLyvsp9iybNqRvm94g  2011-10-03  pcEeHdAJPoFNF23es0kKWg      5   
9991  WJ5mq4EiWYAA4Vif0xDfdg  2011-12-05  EuHX-39FR7tyyG1ElvN1Jw      5   
9992  f96lWMIAUhYIYy9gOktivQ  2009-03-10  YF17z7HWlMj6aezZc-pVEw      5   
9994  L3BSpFvxcNf3T_teitgt6A  2012-03-19  0nxb1gIGFgk3WbC5zwhKZg      5   
9999  pF7uRzygyZsltbmVpjIyvw  2010-10-16  vWSmOhg2ID1MNZHaWapGbA      5   

                                                   text    type  \
23    U can go there n check the car out. If u wanna...  review   
31    Disgusting!  Had a Groupon so my daughter and ...  review   
35    I've eaten here many times, but none as bad as...  review   
61    I have always been a fan of Burlington's deals...  review   
64    Another night meeting friends here.  I have to...  review   
...                                                 ...     ...   
9990  Yes I do rock the hipster joints.  I dig this ...  review   
9991  Only 4 stars? \n\n(A few notes: The folks that...  review   
9992  I'm not normally one to jump at reviewing a ch...  review   
9994  Let's see...what is there NOT to like about Su...  review   
9999  4-5 locations.. all 4.5 star average.. I think...  review   

                     user_id  cool  useful  funny  
23    zRlQEDYd_HKp0VS3hnAffA     0       1      1  
31    8AMn6644NmBf96xGO3w6OA     0       1      0  
35    iwUN95LIaEr75TZE_JC6bg     0       4      3  
61    EPROVap0M19Y6_4uf3eCmQ     0       0      0  
64    MjLAe48XNfYlTeFYca5gMw     0       1      2  
...                      ...   ...     ...    ...  
9990  b92Y3tyWTQQZ5FLifex62Q     1       1      1  
9991  hTau-iNZFwoNsPCaiIUTEA     1       1      0  
9992  W_QXYA7A0IhMrvbckz7eVg     2       3      2  
9994  OzOZv-Knlw3oz9K5Kh5S6A     1       2      1  
9999  KSBFytcdjPKZgXKQnYQdkA     0       0      0  

[4086 rows x 10 columns]

In [88]:
dataset_1_and_5.index = range(0,4086,1)

In [89]:
dataset_1_and_5

business_id        date               review_id  stars  \
0     IJ0o6b8bJFAbG6MjGfBebQ  2010-09-05  Dx9sfFU6Zn0GYOckijom-g      1   
1     vvA3fbps4F9nGlAEYKk_sA  2012-05-04  S9OVpXat8k5YwWCn6FAgXg      1   
2     o1GIYYZJjM6nM03fQs_uEQ  2011-11-30  ApKbwpYJdnhhgP4NbjQw2Q      1   
3     l4vBbCL9QbGiwLuLKwD_bA  2011-11-22  DJVxOfj2Rw9zklC9tU3i1w      1   
4     CEswyP-9SsXRNLR9fFGKKw  2012-05-19  GXj4PNAi095-q9ynPYH3kg      1   
...                      ...         ...                     ...    ...   
4081  R8VwdLyvsp9iybNqRvm94g  2011-10-03  pcEeHdAJPoFNF23es0kKWg      5   
4082  WJ5mq4EiWYAA4Vif0xDfdg  2011-12-05  EuHX-39FR7tyyG1ElvN1Jw      5   
4083  f96lWMIAUhYIYy9gOktivQ  2009-03-10  YF17z7HWlMj6aezZc-pVEw      5   
4084  L3BSpFvxcNf3T_teitgt6A  2012-03-19  0nxb1gIGFgk3WbC5zwhKZg      5   
4085  pF7uRzygyZsltbmVpjIyvw  2010-10-16  vWSmOhg2ID1MNZHaWapGbA      5   

                                                   text    type  \
0     U can go there n check the car out. If u wanna...  review   
1     Disgusting!  Had a Groupon so my daughter and ...  review   
2     I've eaten here many times, but none as bad as...  review   
3     I have always been a fan of Burlington's deals...  review   
4     Another night meeting friends here.  I have to...  review   
...                                                 ...     ...   
4081  Yes I do rock the hipster joints.  I dig this ...  review   
4082  Only 4 stars? \n\n(A few notes: The folks that...  review   
4083  I'm not normally one to jump at reviewing a ch...  review   
4084  Let's see...what is there NOT to like about Su...  review   
4085  4-5 locations.. all 4.5 star average.. I think...  review   

                     user_id  cool  useful  funny  
0     zRlQEDYd_HKp0VS3hnAffA     0       1      1  
1     8AMn6644NmBf96xGO3w6OA     0       1      0  
2     iwUN95LIaEr75TZE_JC6bg     0       4      3  
3     EPROVap0M19Y6_4uf3eCmQ     0       0      0  
4     MjLAe48XNfYlTeFYca5gMw     0       1      2  
...                      ...   ...     ...    ...  
4081  b92Y3tyWTQQZ5FLifex62Q     1       1      1  
4082  hTau-iNZFwoNsPCaiIUTEA     1       1      0  
4083  W_QXYA7A0IhMrvbckz7eVg     2       3      2  
4084  OzOZv-Knlw3oz9K5Kh5S6A     1       2      1  
4085  KSBFytcdjPKZgXKQnYQdkA     0       0      0  

[4086 rows x 10 columns]

In [90]:
#cleaning the texts
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,4086):
    review = re.sub('[^a-zA-Z]' , " ", dataset_1_and_5['text'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words("english")
    all_stopwords.remove('not')
    review =[ps.stem(word)for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [91]:
corpus[4085]

'locat star averag think arizona realli fantast pizza option spinato top pizza fix list semi sweet sauc addict great servic fresh ingredi spici italian favorit chocol chip cooki lace mind alter drug make bodi part romant think cooki btw pm tuesday left minut wait list'

In [92]:
dataset_1_and_5.iloc[:,3]

0       1
1       1
2       1
3       1
4       1
       ..
4081    5
4082    5
4083    5
4084    5
4085    5
Name: stars, Length: 4086, dtype: int64

In [93]:
#creating the bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
y = dataset_1_and_5.iloc[:,3].values

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass input=1500 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [94]:
#splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [96]:
#training the naive bayes model on the training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [97]:
#predicting the test set results
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[5 5]
 [5 5]
 [5 5]
 ...
 [5 5]
 [5 5]
 [5 5]]


In [98]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 77  96]
 [139 506]]


0.7127139364303179

In [99]:
#####################################random forest######################################
###training the random forest  model on the Training set
from  sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [100]:
#predicting the test set results
y_pred = classifier.predict(x_test)

In [101]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 67 106]
 [  3 642]]


0.8667481662591687

In [102]:
#############################kernel-SVM#################################################
###training the kernel svm  model on the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(random_state=0)

In [103]:
#predicting the test set results
y_pred = classifier.predict(x_test)

In [104]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 75  98]
 [  3 642]]


0.8765281173594132

In [105]:
##################################K-NN#######################################
###training the k_nn model on the Training set
from  sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p= 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [106]:
#predicting the test set results
y_pred = classifier.predict(x_test)

In [107]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 35 138]
 [ 17 628]]


0.8105134474327629

In [108]:
##############################logistic##########################################
###training the logistic regression model on the Training set
from  sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [109]:
#predicting the test set results
y_pred = classifier.predict(x_test)

In [110]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[129  44]
 [ 19 626]]


0.9229828850855746

In [111]:
######################################################XGBoost#################

In [112]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train, y_train)

C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:892: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[01:19:28] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [113]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[118  55]
 [  8 637]]


0.9229828850855746